blank_issues_enabled: true
contact_links: []
  - name: General Questions or Discussions
    url: https://github.com/ryanthestark/AI-For-Everyone/discussions
    about: For general questions, use GitHub Discussions
